services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrator:
    image: postgres:16
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./migrations:/migrations:ro
      - ./ops/migrate.sh:/migrate.sh:ro
    entrypoint: ["/bin/bash","-lc"]
    # Use bash to run the file so we don't rely on the executable bit on Windows
    command: "bash /migrate.sh"
    restart: "no"

  api:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      migrator:
        condition: service_completed_successfully
    ports:
      - "5000:5000"

  web:
    build:
      context: ./frontend
    depends_on:
      api:
        condition: service_started
    ports:
      - "8080:80"

volumes:
  dbdata:
