-- 0001_schema.sql
-- Base schema: enum, tables, inline normalization, indexes, trigger.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- enum used by records.file_type
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'record_type') THEN
    CREATE TYPE record_type AS ENUM (
      'WANTED_PERSON','FOREIGN_FUGITIVE','MISSING_PERSON','UNIDENTIFIED_PERSON',
      'STOLEN_VEHICLE','STOLEN_LICENSE_PLATE','STOLEN_BOAT','STOLEN_GUN',
      'STOLEN_ARTICLE','SECURITY','USSS_PROTECTIVE',
      'VIOLENT_CRIMINAL_GANG_MEMBER','TERRORIST_MEMBER','BATF_VIOLENT_FELON',
      'WITSEC_CHARGED','INTERSTATE_ID_INDEX'
    );
  END IF;
END $$;

-- records
CREATE TABLE IF NOT EXISTS records (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  file_type record_type NOT NULL,
  payload JSONB NOT NULL,
  originating_agency VARCHAR(128) NOT NULL,
  originating_case_number VARCHAR(64),
  ncic_number VARCHAR(32),
  status VARCHAR(24) DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  effective_until TIMESTAMPTZ,
  tags TEXT[] NOT NULL DEFAULT '{}'
);
CREATE INDEX IF NOT EXISTS idx_records_file_type        ON records (file_type);
CREATE INDEX IF NOT EXISTS idx_records_effective_until  ON records (effective_until);
CREATE INDEX IF NOT EXISTS idx_records_created_id       ON records (created_at DESC, id DESC);

-- descriptors (normalized_value is generated by DB; inline the normalization)
CREATE TABLE IF NOT EXISTS descriptors (
  id BIGSERIAL PRIMARY KEY,
  record_id UUID NOT NULL REFERENCES records(id) ON DELETE CASCADE,
  key VARCHAR(64) NOT NULL,
  value TEXT NOT NULL,
  normalized_value TEXT GENERATED ALWAYS AS (
    UPPER( regexp_replace(value, '\s+', '', 'g') )
  ) STORED
);
CREATE INDEX IF NOT EXISTS idx_descriptors_record       ON descriptors (record_id);
CREATE INDEX IF NOT EXISTS idx_descriptors_key_norm     ON descriptors (key, normalized_value);

-- audit_log
CREATE TABLE IF NOT EXISTS audit_log (
  id BIGSERIAL PRIMARY KEY,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  actor_id UUID,
  actor_role VARCHAR(64),
  action VARCHAR(32) NOT NULL,
  record_id UUID,
  context JSONB
);

-- Optional: auto-set 48h expiry for Temporary Felony Want flag in payload
CREATE OR REPLACE FUNCTION schedule_tfw_purge() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  IF (NEW.payload ? 'temporary_felony_want')
     AND coalesce((NEW.payload->>'temporary_felony_want')::boolean, false) THEN
    IF NEW.effective_until IS NULL THEN
      NEW.effective_until := now() + interval '48 hours';
    END IF;
  END IF;
  RETURN NEW;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_tfw_purge') THEN
    CREATE TRIGGER trg_tfw_purge
    BEFORE INSERT ON records
    FOR EACH ROW EXECUTE FUNCTION schedule_tfw_purge();
  END IF;
END $$;

COMMIT;
