from flask import Blueprint, request, jsonify, abort
from flask_jwt_extended import get_jwt, get_jwt_identity
from sqlalchemy import and_, func, tuple_, distinct
from . import db
from .models import Record, Descriptor, AuditLog, RecordType
from .services.descriptors import build_descriptors, normalize
from .authz import require_role
from .policy import redact_payload

bp = Blueprint("records", __name__, url_prefix="/api/records")

def serialize_record(r, role: str, include_descriptors: bool = False):
    item = {
        "id": str(r.id),
        "file_type": r.file_type.value,
        "originating_agency": r.originating_agency,
        "originating_case_number": r.originating_case_number,
        "ncic_number": r.ncic_number,
        "status": r.status,
        "created_at": r.created_at.isoformat(),
        "effective_until": r.effective_until.isoformat() if r.effective_until else None,
        "payload": redact_payload(r.payload, role),
    }
    if include_descriptors:
        ds = Descriptor.query.filter_by(record_id=r.id).order_by(Descriptor.key.asc()).all()
        item["descriptors"] = [{"key": d.key, "value": d.value} for d in ds]
    return item


@bp.post("")
@require_role(["ADMIN", "ANALYST"])
def create_record():
    data = request.get_json(force=True)

    try:
        rtype = RecordType(data["file_type"])
    except Exception:
        abort(400, description="Invalid file_type")

    payload = data.get("payload")
    if not isinstance(payload, dict):
        abort(400, description="payload must be an object")

    rec = Record(
        file_type=rtype,
        payload=payload,
        originating_agency=data.get("originating_agency", "TEST-AGENCY"),
        originating_case_number=data.get("originating_case_number"),
        ncic_number=data.get("ncic_number"),
    )
    db.session.add(rec)
    db.session.flush()  # get rec.id

    # descriptors (normalized_value is generated by DB)
    for d in build_descriptors(rec):
        db.session.add(d)

    # audit
    db.session.add(
        AuditLog(
            action="CREATE",
            actor_id=get_jwt_identity(),
            actor_role=(get_jwt() or {}).get("role"),
            record_id=rec.id,
            context={"file_type": rec.file_type.value},
        )
    )

    db.session.commit()
    return jsonify({"id": str(rec.id)}), 201


def _as_int(v, default):
    try:
        return int(v)
    except Exception:
        return default


@bp.get("")
@require_role(["ADMIN", "ANALYST", "DISPATCH_TRAINER"])
def search_records():
    q = request.args
    clauses = []

    # file type filter
    ft = q.get("file_type")
    if ft:
        try:
            clauses.append(Record.file_type == RecordType(ft))
        except Exception:
            abort(400, description="Invalid file_type")

    # descriptor filters (match ALL provided)
    keys = [
        "VIN", "PLATE", "SERIAL", "NAME", "DOB", "FBI_NUMBER", "SSN", "DRIVERS_NUMBER", "OAN",
        "HULL_NUMBER", "REGISTRATION", "ISSUER", "OWNER_SSN", "WARRANT_NUMBER", "ORIGINATING_CASE_NUMBER",
    ]
    filt_pairs = [(k, normalize(q.get(k))) for k in keys if q.get(k)]
    if filt_pairs:
        # rows whose (key,normalized_value) include ALL pairs
        sub = (
            db.session.query(Descriptor.record_id)
            .filter(tuple_(Descriptor.key, Descriptor.normalized_value).in_(filt_pairs))
            .group_by(Descriptor.record_id)
            .having(func.count(distinct(Descriptor.key)) == len(filt_pairs))
            .subquery()
        )
        clauses.append(Record.id.in_(db.session.query(sub.c.record_id)))

    # base query with filters
    base = Record.query.filter(and_(*clauses)) if clauses else Record.query

    # role & pagination
    jwt = (get_jwt() or {})
    role = jwt.get("role", "ANALYST")

    limit = _as_int(q.get("limit", 100), 100)
    offset = _as_int(q.get("offset", 0), 0)
    max_limit = 5000 if role in ("ADMIN", "ANALYST") else 1000
    limit = max(1, min(limit, max_limit))
    offset = max(0, offset)

    # stable ordering for paging
    ordered = base.order_by(Record.created_at.desc(), Record.id.desc())

    rows = ordered.limit(limit).offset(offset).all()

    items = [serialize_record(r, role) for r in rows]

    # audit (non-blocking info only)
    db.session.add(
        AuditLog(
            action="SEARCH",
            actor_id=get_jwt_identity(),
            actor_role=role,
            context={
                "file_type": ft,
                "filters": [k for k, _ in filt_pairs],
                "limit": limit,
                "offset": offset,
                "returned": len(items),
            },
        )
    )
    db.session.commit()

    return jsonify(
        {
            "items": items,
            "limit": limit,
            "offset": offset,
            "returned": len(items),
            "has_more": len(items) == limit,
        }
    )

@bp.get("/<rid>")
@require_role(["ADMIN", "ANALYST", "DISPATCH_TRAINER"])
def get_record(rid):
    rec = Record.query.get(rid)
    if not rec:
        abort(404)
    role = (get_jwt() or {}).get("role", "ANALYST")
    include_desc = request.args.get("include_descriptors") == "1"
    out = serialize_record(rec, role, include_desc)

    db.session.add(
        AuditLog(
            action="READ",
            actor_id=get_jwt_identity(),
            actor_role=role,
            record_id=rec.id,
            context={"include_descriptors": include_desc},
        )
    )
    db.session.commit()
    return jsonify(out)

@bp.post("/clear/<rid>")
@require_role(["ADMIN", "ANALYST"])
def clear_record(rid):
    rec = Record.query.get(rid)
    if not rec:
        abort(404)
    rec.status = "CLEARED"
    db.session.add(
        AuditLog(
            action="CLEAR",
            actor_id=get_jwt_identity(),
            actor_role=(get_jwt() or {}).get("role"),
            record_id=rec.id,
        )
    )
    db.session.commit()
    return {"ok": True}
